function settings = resolveCohortEvaluationSettings(S)
%RESOLVECOHORTEVALUATIONSETTINGS Keep planning and final evaluation distinct.
    required = {'planning_collision_sample_spacing_m', ...
        'final_verification_spacing_m','main_min_collision_samples'};
    for i = 1:numel(required)
        if ~isfield(S,required{i})
            error('Validation:CohortSchema', ...
                ['The cohort lacks %s. Use a cohort generated by the revised ', ...
                'main driver; do not relabel historical results.'],required{i});
        end
        validateattributes(S.(required{i}),{'numeric'}, ...
            {'scalar','real','finite','positive'},mfilename,required{i});
    end
    settings = struct('PlanningSpacingM',double(S.planning_collision_sample_spacing_m), ...
        'FinalSpacingM',double(S.final_verification_spacing_m), ...
        'MinSamples',double(S.main_min_collision_samples));
    validateattributes(settings.MinSamples,{'numeric'},{'integer','>=',2});
    if settings.FinalSpacingM > settings.PlanningSpacingM
        error('Validation:ResolutionOrder','Final sampling must be at least as fine as planning sampling.');
    end
    if isfield(S,'main_collision_sample_spacing_m') && ...
            ~isequal(S.main_collision_sample_spacing_m,S.final_verification_spacing_m)
        error('Validation:ResolutionMetadata','The main outcome spacing must equal the final verification spacing.');
    end
    current = validationProvenance();
    if isfield(S,'validation_source')
        if ~isequaln(S.validation_source,current)
            error('Validation:SourceMismatch', ...
                'The saved cohort and current scientific implementation differ. Use the matching source or regenerate the cohort.');
        end
    else
        warning('Validation:UnverifiedSource', ...
            ['This revised-format cohort predates source fingerprints. Its source version ', ...
            'cannot be verified automatically; confirm it was generated by the current implementation.']);
    end
end
