function results=runRemainingValidationExperiments(userOpts)
% Continue only the validation stages after the completed core experiments.
if nargin<1, userOpts=struct(); end
projectDir=fileparts(mfilename('fullpath'));
% Budget analysis reruns planners and is opt-in because the study makes no
% equal-budget claim; reported conclusions use prespecified method budgets.
defaults=struct('RunWeights',true,'RunResolution',true, ...
    'RunSummary',true,'RunBudget',false,'CheckOnly',false, ...
    'CohortFile',fullfile(projectDir,'main_experiment_cohort.mat'), ...
    'WeightOptions',struct(),'ResolutionOptions',struct(), ...
    'BudgetOptions',struct());
names=fieldnames(userOpts);
for i=1:numel(names)
    if ~isfield(defaults,names{i})
        error('RemainingValidation:UnknownOption','Unknown option: %s',names{i});
    end
    defaults.(names{i})=userOpts.(names{i});
end
suiteOptions=struct('RunFigure78',false,'RunMain',false, ...
    'RunClusterStats',false,'RunWeights',defaults.RunWeights, ...
    'RunResolution',defaults.RunResolution,'RunSummary',defaults.RunSummary, ...
    'RunBudget',defaults.RunBudget,'CheckOnly',defaults.CheckOnly, ...
    'CohortFile',defaults.CohortFile,'WeightOptions',defaults.WeightOptions, ...
    'ResolutionOptions',defaults.ResolutionOptions, ...
    'BudgetOptions',defaults.BudgetOptions);
results=runAllValidationExperiments(suiteOptions);
end
